// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { ActivityActivityGetData, ActivityActivityGetErrors, ActivityActivityGetResponses, ConceptDetailConceptsPathGetData, ConceptDetailConceptsPathGetErrors, ConceptDetailConceptsPathGetResponses, GraphGraphGetData, GraphGraphGetErrors, GraphGraphGetResponses, GrepGrepGetData, GrepGrepGetErrors, GrepGrepGetResponses, ListConceptsConceptsGetData, ListConceptsConceptsGetErrors, ListConceptsConceptsGetResponses, LoginSessionPostData, LoginSessionPostErrors, LoginSessionPostResponses, LogoutSessionDeleteData, LogoutSessionDeleteResponses, OpenapiSchemaOpenapiJsonGetData, OpenapiSchemaOpenapiJsonGetResponses, SearchSearchGetData, SearchSearchGetErrors, SearchSearchGetResponses, StatsStatsGetData, StatsStatsGetErrors, StatsStatsGetResponses, StatsTimeseriesStatsTimeseriesGetData, StatsTimeseriesStatsTimeseriesGetErrors, StatsTimeseriesStatsTimeseriesGetResponses, TenantsTenantsGetData, TenantsTenantsGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Logout
 */
export const logoutSessionDelete = <ThrowOnError extends boolean = false>(options?: Options<LogoutSessionDeleteData, ThrowOnError>): RequestResult<LogoutSessionDeleteResponses, unknown, ThrowOnError> => (options?.client ?? client).delete<LogoutSessionDeleteResponses, unknown, ThrowOnError>({ url: '/session', ...options });

/**
 * Login
 */
export const loginSessionPost = <ThrowOnError extends boolean = false>(options: Options<LoginSessionPostData, ThrowOnError>): RequestResult<LoginSessionPostResponses, LoginSessionPostErrors, ThrowOnError> => (options.client ?? client).post<LoginSessionPostResponses, LoginSessionPostErrors, ThrowOnError>({
    url: '/session',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Openapi Schema
 */
export const openapiSchemaOpenapiJsonGet = <ThrowOnError extends boolean = false>(options?: Options<OpenapiSchemaOpenapiJsonGetData, ThrowOnError>): RequestResult<OpenapiSchemaOpenapiJsonGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<OpenapiSchemaOpenapiJsonGetResponses, unknown, ThrowOnError>({ url: '/openapi.json', ...options });

/**
 * Tenants
 */
export const tenantsTenantsGet = <ThrowOnError extends boolean = false>(options?: Options<TenantsTenantsGetData, ThrowOnError>): RequestResult<TenantsTenantsGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<TenantsTenantsGetResponses, unknown, ThrowOnError>({ url: '/tenants', ...options });

/**
 * Stats
 */
export const statsStatsGet = <ThrowOnError extends boolean = false>(options?: Options<StatsStatsGetData, ThrowOnError>): RequestResult<StatsStatsGetResponses, StatsStatsGetErrors, ThrowOnError> => (options?.client ?? client).get<StatsStatsGetResponses, StatsStatsGetErrors, ThrowOnError>({ url: '/stats', ...options });

/**
 * Stats Timeseries
 */
export const statsTimeseriesStatsTimeseriesGet = <ThrowOnError extends boolean = false>(options?: Options<StatsTimeseriesStatsTimeseriesGetData, ThrowOnError>): RequestResult<StatsTimeseriesStatsTimeseriesGetResponses, StatsTimeseriesStatsTimeseriesGetErrors, ThrowOnError> => (options?.client ?? client).get<StatsTimeseriesStatsTimeseriesGetResponses, StatsTimeseriesStatsTimeseriesGetErrors, ThrowOnError>({ url: '/stats/timeseries', ...options });

/**
 * List Concepts
 */
export const listConceptsConceptsGet = <ThrowOnError extends boolean = false>(options?: Options<ListConceptsConceptsGetData, ThrowOnError>): RequestResult<ListConceptsConceptsGetResponses, ListConceptsConceptsGetErrors, ThrowOnError> => (options?.client ?? client).get<ListConceptsConceptsGetResponses, ListConceptsConceptsGetErrors, ThrowOnError>({ url: '/concepts', ...options });

/**
 * Concept Detail
 */
export const conceptDetailConceptsPathGet = <ThrowOnError extends boolean = false>(options: Options<ConceptDetailConceptsPathGetData, ThrowOnError>): RequestResult<ConceptDetailConceptsPathGetResponses, ConceptDetailConceptsPathGetErrors, ThrowOnError> => (options.client ?? client).get<ConceptDetailConceptsPathGetResponses, ConceptDetailConceptsPathGetErrors, ThrowOnError>({ url: '/concepts/{path}', ...options });

/**
 * Search
 */
export const searchSearchGet = <ThrowOnError extends boolean = false>(options: Options<SearchSearchGetData, ThrowOnError>): RequestResult<SearchSearchGetResponses, SearchSearchGetErrors, ThrowOnError> => (options.client ?? client).get<SearchSearchGetResponses, SearchSearchGetErrors, ThrowOnError>({ url: '/search', ...options });

/**
 * Grep
 */
export const grepGrepGet = <ThrowOnError extends boolean = false>(options: Options<GrepGrepGetData, ThrowOnError>): RequestResult<GrepGrepGetResponses, GrepGrepGetErrors, ThrowOnError> => (options.client ?? client).get<GrepGrepGetResponses, GrepGrepGetErrors, ThrowOnError>({ url: '/grep', ...options });

/**
 * Graph
 */
export const graphGraphGet = <ThrowOnError extends boolean = false>(options: Options<GraphGraphGetData, ThrowOnError>): RequestResult<GraphGraphGetResponses, GraphGraphGetErrors, ThrowOnError> => (options.client ?? client).get<GraphGraphGetResponses, GraphGraphGetErrors, ThrowOnError>({ url: '/graph', ...options });

/**
 * Activity
 */
export const activityActivityGet = <ThrowOnError extends boolean = false>(options?: Options<ActivityActivityGetData, ThrowOnError>): RequestResult<ActivityActivityGetResponses, ActivityActivityGetErrors, ThrowOnError> => (options?.client ?? client).get<ActivityActivityGetResponses, ActivityActivityGetErrors, ThrowOnError>({ url: '/activity', ...options });
