// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * ConceptDetail
 */
export type ConceptDetail = {
    /**
     * Path
     */
    path: string;
    /**
     * Type
     */
    type: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Body
     */
    body: string;
    /**
     * Frontmatter
     */
    frontmatter: {
        [key: string]: unknown;
    };
    /**
     * Links
     */
    links: Array<string>;
    /**
     * Version
     */
    version: number;
    /**
     * Backlinks
     */
    backlinks: Array<string>;
    /**
     * Revisions
     */
    revisions: Array<RevisionOut>;
};

/**
 * ConceptPage
 */
export type ConceptPage = {
    /**
     * Items
     */
    items: Array<SummaryOut>;
    /**
     * Total
     */
    total: number;
};

/**
 * Credentials
 */
export type Credentials = {
    /**
     * Password
     */
    password: string;
};

/**
 * DailyWrite
 */
export type DailyWrite = {
    /**
     * Date
     */
    date: string;
    /**
     * Count
     */
    count: number;
};

/**
 * GraphOut
 */
export type GraphOut = {
    /**
     * Nodes
     */
    nodes: Array<NodeOut>;
    /**
     * Edges
     */
    edges: Array<[
        string,
        string
    ]>;
    /**
     * Truncated
     */
    truncated: boolean;
};

/**
 * GrepHit
 */
export type GrepHit = {
    /**
     * Path
     */
    path: string;
    /**
     * Snippet
     */
    snippet: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HitOut
 */
export type HitOut = {
    /**
     * Path
     */
    path: string;
    /**
     * Type
     */
    type: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Score
     */
    score: number;
};

/**
 * NodeOut
 */
export type NodeOut = {
    /**
     * Path
     */
    path: string;
    /**
     * Type
     */
    type: string;
    /**
     * Title
     */
    title: string;
    /**
     * Exists
     */
    exists: boolean;
};

/**
 * RevisionOut
 */
export type RevisionOut = {
    /**
     * Path
     */
    path: string;
    /**
     * Version
     */
    version: number;
    /**
     * Op
     */
    op: string;
    /**
     * Updated By
     */
    updated_by: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
};

/**
 * SummaryOut
 */
export type SummaryOut = {
    /**
     * Path
     */
    path: string;
    /**
     * Type
     */
    type: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Version
     */
    version: number;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
};

/**
 * TenantCount
 */
export type TenantCount = {
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Concepts
     */
    concepts: number;
};

/**
 * TotalsOut
 */
export type TotalsOut = {
    /**
     * Concepts
     */
    concepts: number;
    /**
     * By Type
     */
    by_type: {
        [key: string]: number;
    };
    /**
     * Revisions
     */
    revisions: number;
    /**
     * Links
     */
    links: number;
    /**
     * Orphans
     */
    orphans: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LogoutSessionDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/session';
};

export type LogoutSessionDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutSessionDeleteResponse = LogoutSessionDeleteResponses[keyof LogoutSessionDeleteResponses];

export type LoginSessionPostData = {
    body: Credentials;
    path?: never;
    query?: never;
    url: '/session';
};

export type LoginSessionPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginSessionPostError = LoginSessionPostErrors[keyof LoginSessionPostErrors];

export type LoginSessionPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LoginSessionPostResponse = LoginSessionPostResponses[keyof LoginSessionPostResponses];

export type OpenapiSchemaOpenapiJsonGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/openapi.json';
};

export type OpenapiSchemaOpenapiJsonGetResponses = {
    /**
     * Response Openapi Schema Openapi Json Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type OpenapiSchemaOpenapiJsonGetResponse = OpenapiSchemaOpenapiJsonGetResponses[keyof OpenapiSchemaOpenapiJsonGetResponses];

export type TenantsTenantsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tenants';
};

export type TenantsTenantsGetResponses = {
    /**
     * Response Tenants Tenants Get
     *
     * Successful Response
     */
    200: Array<TenantCount>;
};

export type TenantsTenantsGetResponse = TenantsTenantsGetResponses[keyof TenantsTenantsGetResponses];

export type StatsStatsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Tenant
         */
        tenant?: string | null;
    };
    url: '/stats';
};

export type StatsStatsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StatsStatsGetError = StatsStatsGetErrors[keyof StatsStatsGetErrors];

export type StatsStatsGetResponses = {
    /**
     * Successful Response
     */
    200: TotalsOut;
};

export type StatsStatsGetResponse = StatsStatsGetResponses[keyof StatsStatsGetResponses];

export type StatsTimeseriesStatsTimeseriesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Tenant
         */
        tenant?: string | null;
        /**
         * Days
         */
        days?: number;
    };
    url: '/stats/timeseries';
};

export type StatsTimeseriesStatsTimeseriesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StatsTimeseriesStatsTimeseriesGetError = StatsTimeseriesStatsTimeseriesGetErrors[keyof StatsTimeseriesStatsTimeseriesGetErrors];

export type StatsTimeseriesStatsTimeseriesGetResponses = {
    /**
     * Response Stats Timeseries Stats Timeseries Get
     *
     * Successful Response
     */
    200: Array<DailyWrite>;
};

export type StatsTimeseriesStatsTimeseriesGetResponse = StatsTimeseriesStatsTimeseriesGetResponses[keyof StatsTimeseriesStatsTimeseriesGetResponses];

export type ListConceptsConceptsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Tenant
         */
        tenant?: string | null;
        /**
         * Prefix
         */
        prefix?: string;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/concepts';
};

export type ListConceptsConceptsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListConceptsConceptsGetError = ListConceptsConceptsGetErrors[keyof ListConceptsConceptsGetErrors];

export type ListConceptsConceptsGetResponses = {
    /**
     * Successful Response
     */
    200: ConceptPage;
};

export type ListConceptsConceptsGetResponse = ListConceptsConceptsGetResponses[keyof ListConceptsConceptsGetResponses];

export type ConceptDetailConceptsPathGetData = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query: {
        /**
         * Tenant
         */
        tenant: string;
    };
    url: '/concepts/{path}';
};

export type ConceptDetailConceptsPathGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConceptDetailConceptsPathGetError = ConceptDetailConceptsPathGetErrors[keyof ConceptDetailConceptsPathGetErrors];

export type ConceptDetailConceptsPathGetResponses = {
    /**
     * Successful Response
     */
    200: ConceptDetail;
};

export type ConceptDetailConceptsPathGetResponse = ConceptDetailConceptsPathGetResponses[keyof ConceptDetailConceptsPathGetResponses];

export type SearchSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Tenant
         */
        tenant: string;
        /**
         * Q
         */
        q: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/search';
};

export type SearchSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchSearchGetError = SearchSearchGetErrors[keyof SearchSearchGetErrors];

export type SearchSearchGetResponses = {
    /**
     * Response Search Search Get
     *
     * Successful Response
     */
    200: Array<HitOut>;
};

export type SearchSearchGetResponse = SearchSearchGetResponses[keyof SearchSearchGetResponses];

export type GrepGrepGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Tenant
         */
        tenant: string;
        /**
         * Pattern
         */
        pattern: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/grep';
};

export type GrepGrepGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GrepGrepGetError = GrepGrepGetErrors[keyof GrepGrepGetErrors];

export type GrepGrepGetResponses = {
    /**
     * Response Grep Grep Get
     *
     * Successful Response
     */
    200: Array<GrepHit>;
};

export type GrepGrepGetResponse = GrepGrepGetResponses[keyof GrepGrepGetResponses];

export type ActivityActivityGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Tenant
         */
        tenant?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/activity';
};

export type ActivityActivityGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ActivityActivityGetError = ActivityActivityGetErrors[keyof ActivityActivityGetErrors];

export type ActivityActivityGetResponses = {
    /**
     * Response Activity Activity Get
     *
     * Successful Response
     */
    200: Array<RevisionOut>;
};

export type ActivityActivityGetResponse = ActivityActivityGetResponses[keyof ActivityActivityGetResponses];

export type GraphGraphGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Tenant
         */
        tenant?: string | null;
        /**
         * Prefix
         */
        prefix?: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/graph';
};

export type GraphGraphGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GraphGraphGetError = GraphGraphGetErrors[keyof GraphGraphGetErrors];

export type GraphGraphGetResponses = {
    /**
     * Successful Response
     */
    200: GraphOut;
};

export type GraphGraphGetResponse = GraphGraphGetResponses[keyof GraphGraphGetResponses];
