/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConceptsIndexRouteImport } from './routes/concepts.index'
import { Route as ConceptsSplatRouteImport } from './routes/concepts.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsIndexRoute = ConceptsIndexRouteImport.update({
  id: '/concepts/',
  path: '/concepts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsSplatRoute = ConceptsSplatRouteImport.update({
  id: '/concepts/$',
  path: '/concepts/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/login': typeof LoginRoute
  '/concepts/$': typeof ConceptsSplatRoute
  '/concepts/': typeof ConceptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/login': typeof LoginRoute
  '/concepts/$': typeof ConceptsSplatRoute
  '/concepts': typeof ConceptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/login': typeof LoginRoute
  '/concepts/$': typeof ConceptsSplatRoute
  '/concepts/': typeof ConceptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/graph' | '/login' | '/concepts/$' | '/concepts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/graph' | '/login' | '/concepts/$' | '/concepts'
  id: '__root__' | '/' | '/graph' | '/login' | '/concepts/$' | '/concepts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphRoute: typeof GraphRoute
  LoginRoute: typeof LoginRoute
  ConceptsSplatRoute: typeof ConceptsSplatRoute
  ConceptsIndexRoute: typeof ConceptsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts/': {
      id: '/concepts/'
      path: '/concepts'
      fullPath: '/concepts/'
      preLoaderRoute: typeof ConceptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts/$': {
      id: '/concepts/$'
      path: '/concepts/$'
      fullPath: '/concepts/$'
      preLoaderRoute: typeof ConceptsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphRoute: GraphRoute,
  LoginRoute: LoginRoute,
  ConceptsSplatRoute: ConceptsSplatRoute,
  ConceptsIndexRoute: ConceptsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
